version: '3.8'

services:
  app:
    build: ./
    restart: unless-stopped
    ports:
      - 3000:3000
    working_dir: /app
    volumes:
      - ./:/app
    depends_on:
      - postgres
    env_file:
      - .env

  postgres:
    image: postgres:15
    container_name: postgres_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./databaseSetUp.sql:/docker-entrypoint-initdb.d/databaseSetUp.sql
    env_file:
      - .env


volumes:
  db_data:
